export const siteConfig = {
  name: 'SavDown',
  tagline: 'The Free Video Downloader',
  description:
    'SavDown is a fast, free video downloader for YouTube, TikTok, Instagram, Facebook, Pinterest, and X. No watermarks, free daily credits, with AI-powered tools on the way.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
  ogImage: '/og-default.svg',
  twitterHandle: '@SavDownload',
  footerDescription:
    'SavDown is the fast, private way to save videos, reels, and thumbnails from the platforms you use every day. No watermarks, no clutter, free daily credits.',
  social: [
    { label: 'Facebook', href: 'https://www.facebook.com/profile.php?id=61592887680787', icon: 'facebook' },
    { label: 'Instagram', href: 'https://www.instagram.com/savdownload/?hl=en', icon: 'instagram' },
    { label: 'X (Twitter)', href: 'https://x.com/SavDownload', icon: 'x' },
    { label: 'Pinterest', href: 'https://www.pinterest.com/savdownload/_profile/', icon: 'pinterest' },
    { label: 'LinkedIn', href: 'https://www.linkedin.com/company/savdown/', icon: 'linkedin' },
    { label: 'Reddit', href: 'https://www.reddit.com/user/SavDownload/', icon: 'reddit' },
  ],
  keywords: [
    'social media downloader',
    'video downloader',
    'youtube downloader',
    'tiktok downloader',
    'instagram reels downloader',
    'facebook video downloader',
    'pinterest video downloader',
    'x video downloader',
  ],
  navigation: [
    { label: 'Tools', href: '/tools' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'Blog', href: '/blog' },
    { label: 'FAQ', href: '/faq' },
    { label: 'About', href: '/about' },
    { label: 'Contact Us', href: '/contact' },
  ],
  footerLinks: {
    'All Tools': [
      { label: 'Browse every tool', href: '/tools' },
      { label: 'Popular downloaders', href: '/tools#downloaders' },
      { label: 'Image tools', href: '/tools#image' },
      { label: 'Video tools', href: '/tools#video' },
      { label: 'PDF tools', href: '/tools#pdf' },
      { label: 'AI tools', href: '/tools#ai' },
      { label: 'SEO tools', href: '/tools#seo' },
      { label: 'Utility tools', href: '/tools#utility' },
    ],
    'Social Media Downloaders': [
      { label: 'YouTube Downloader', href: '/tools/youtube-video-downloader' },
      { label: 'TikTok Downloader', href: '/tools/tiktok-video-downloader' },
      { label: 'Instagram Reels', href: '/tools/instagram-reels-downloader' },
      { label: 'Facebook Video', href: '/tools/facebook-video-downloader' },
      { label: 'Pinterest Video', href: '/tools/pinterest-video-downloader' },
      { label: 'X (Twitter) Video', href: '/tools/x-video-downloader' },
    ],
    'Video Downloaders': [
      { label: 'YouTube Video', href: '/tools/youtube-video-downloader' },
      { label: 'YouTube Shorts', href: '/tools/youtube-shorts-downloader' },
      { label: 'YouTube Playlist', href: '/tools/youtube-playlist-downloader' },
      { label: 'TikTok Video', href: '/tools/tiktok-video-downloader' },
      { label: 'Facebook Reels', href: '/tools/facebook-reels-downloader' },
      { label: 'Pinterest Video', href: '/tools/pinterest-video-downloader' },
    ],
    'Audio Downloaders': [
      { label: 'YouTube to MP3', href: '/tools/youtube-to-mp3' },
      { label: 'TikTok to MP3', href: '/tools/tiktok-to-mp3' },
      { label: 'Video to MP3', href: '/tools/video-to-mp3' },
    ],
    'Image Downloaders': [
      { label: 'Instagram Photos', href: '/tools/instagram-photo-downloader' },
      { label: 'Instagram Profile Picture', href: '/tools/instagram-profile-picture-downloader' },
      { label: 'Pinterest Images', href: '/tools/pinterest-image-downloader' },
      { label: 'YouTube Thumbnails', href: '/tools/youtube-thumbnail-downloader' },
      { label: 'TikTok Thumbnails', href: '/tools/tiktok-thumbnail-downloader' },
    ],
    Resources: [
      { label: 'Blog', href: '/blog' },
      { label: 'Guides', href: '/blog' },
      { label: 'FAQ', href: '/faq' },
      { label: 'Pricing', href: '/pricing' },
      { label: 'Search tools', href: '/search' },
    ],
    Company: [
      { label: 'About Us', href: '/about' },
      { label: 'Contact Us', href: '/contact' },
      { label: 'Customer Reviews', href: '/reviews' },
      { label: 'Sign In', href: '/login' },
      { label: 'My Account', href: '/account' },
      { label: 'Billing', href: '/account/billing' },
    ],
  },
  /** Policy links rendered in the footer's bottom bar (kept out of the column grid). */
  legalLinks: [
    { label: 'Privacy Policy', href: '/privacy' },
    { label: 'Terms of Service', href: '/terms' },
    { label: 'Cookie Policy', href: '/cookies' },
    { label: 'DMCA', href: '/dmca' },
    { label: 'Sitemap', href: '/sitemap.xml' },
  ],
} as const;
