ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'Guides';
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "coverAlt" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "ogImage" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "primaryKeyword" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "secondaryKeywordsJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "canonicalUrl" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "toolSlug" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "readingTimeMinutes" INTEGER;
